apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: dev-

# JsonPatch의 RFC 번호 포함
patchesJson6902:
# 타켓을 직접 명시하여 지정
- target:
    version: v1
    kind: Deployment
    name: hello
  path: resources.yaml
- target:
    version: v1
    kind: Service
    name: hello
  path: service.yaml
