---
- name: "Initialize instance for ansible"
  hosts: default
  become: true

  tasks:
  # python 세팅 작업
  - name: "Install pip"
    apt:
      name:
      - "python3-pip"
      - "python3-setuptools"
      state: present
      update_cache: yes

  - name: "Install Dependencies"
    # python 패키지 설치
    pip:
      name:
      - "virtualenv"

  - name: "Install Ansible"
    pip:
      name: ansible
      version: "{{ ansible_install_version | default(omit) }}"
