apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: fastcampus
spec:
  limits:
  # 보통은 Container 레벨에서 많이 제한
  - type: Container
    # 기본적으로 할당될 값
    default:
      memory: 128Mi
      cpu: 100m
    defaultRequest:
      memory: 64Mi
      cpu: 50m
    # 설정할 범위
    max:
      memory: 1Gi
      cpu: 1000m
    min:
      memory: 16Mi
      cpu: 10m
  - type: Pod
  - type: PersistentVolumeClaim
    min:
      storage: 100Mi
    max:
      storage: 1Gi
