apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      # docker-registry type을 여러개 설정 가능
      # containers 하위의 이미지를 가져올때 사용
      # 빈번하게 이미지를 가져올 때 유용
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: fastcampus
