apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
# base64로 인코딩된 값 존재, base64로 decoding하면 확인 가능
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmYXN0Y2FtcHVzIiwicGFzc3dvcmQiOiJmYXN0Y2FtcHVzIiwiYXV0aCI6IlptRnpkR05oYlhCMWN6cG1ZWE4wWTJGdGNIVnoifX19
