apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 디렉터리를 포함하도록 설정
# 각 디렉터리내에는 kustomization.yaml이 존재해야 함
resources:
- grafana/
- hello/

# deployment object에 대한 patch
## replica 설정을 수정함
replicas:
- name: grafana
  count: 2
- name: hello
  count: 1

# 두가지 목적으로 사용
## 1. 이미지 레지스트리 위치 변경
## 2. 이미지 버전 변경
images:
- name: grafana/grafana
  newTag: "8.2.2" # 버전 업그레이드, 롤백 가능
- name: nginxdemos/hello
  newName: nginx # 기본 이미지의 위치 변경 가능
  newTag: "latest"
