apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-preferred
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:plain-text
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      affinity:
        nodeAffinity:
          # Soft rule
          preferredDuringSchedulingIgnoredDuringExecution:
          # 0~100, scoring을 통해 배치 우선순위 결정
          - weight: 40
            preference:
              matchExpressions:
              - key: team
                operator: In
                values:
                - green
