apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  # Job이 최대 실행될 수 있는 timeout 설정
  ## 3 secs를 의미
  activeDeadlineSeconds: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: ubuntu:focal
        # sleep 5;로 두어 일부러 timeout이 일어나도록
        command: ["sh", "-c", "sleep 5; echo Hello World!"]
