apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
data:
  # configmap의 키
  # filebeat에 대한 설정 정의(filebeat 설정)
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    http:
      enabled: true
      host: 0.0.0.0
      port: 5066

    output.console:
      enabled: true
